### ISSUE TITLE
🧱 Create a MTurk helper library

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/mturk-helper#3]
As an experiment manager, I want a tool that helps me to launch HITs and pay participants so that I minimize mistakes and ensure a consistent and helpful recruiting process for participants.

This tool will be an independent node package that can be imported into other projects. It will comprise a set of routines that tools such as empirica can call on to set up and pay MTurk HITs. 

Basic tasks such as creating HITs, paying workers, etc. will be wrapped to simplify credentials, sync/async issues, error handling, depagination, rate limiting and request batching. (https://github.com/Watts-Lab/mturk-helper/issues/5)

Some higher-level tasks will provide abstrations on top of those basic tasks. For example, a function that takes HIT launch sequences specified in a [manifest file](https://github.com/Watts-Lab/mturk-helper/issues/1) that also serves as documentation for our recruitment process.

# Requirements
- [ ] should be able to take a manifest file and release HITs according to that manifest. 

function like:
```js
launchHITSequence({manifestFileName, sequenceName, launchDate, excludeBy, ...rest})
```
other arguments passed overwrite options from the manifest file at the sequence level.
- [ ] should have a periodic watchdog that queries to make sure that the HITs that are released match what should be released according to the manifest
- [ ] should provide a function that lets us check the status of HITs (number of assignments accepted, completed, etc)
- [ ] needs to make sure that during a "sequence" of HITs, workers can only sign up for one of the hits in the sequences. 
- [ ] should be able to submit payment and bonuses to workers
- [ ] should be able to fill in some string template items such as`${launchDate}`

# Toolsuite
- GH repo here: https://github.com/Watts-Lab/mturk-helper
- As this is a place where robust code is important, we'll use typescript.
- We don't have a front end, so instead of using cypress for e2e testing, we'll use Jest for unit tests.
- (CIS 350 uses Jest, so this is probably as good a reason as any to use that particular framework).
- We want to be able to share the package on npmjs, so we'll use rollup to build the package. (Mostly because of existing familiarity in the team)

# Resources
https://www.thisdot.co/blog/how-to-setup-a-typescript-project-using-rollup-js

**Comment by shapeseas** [comment]
Hey @JamesPHoughton another helpful feature here could be a tag system of some sort, especially a system that facilitates cost accounting. I could imagine `project` or `researcher` tag would be the most important, and would even suggest that those are required as part of the payment. 

I think this sort of functionality would require the project/researcher to be mapped to the HIT ID outside MTurk as there is no way to save custom info in MTurk as far as I know. So I imagine one approach would be to have these fields be part of the manifest file?
